image:
  file: .gitpod.Dockerfile

tasks: 

    - name: RunFlask
      before: pipenv --three
      init: pipenv install flask
      
    - name: StartUpApp
      init: pyenv shell 3.8.13
      command: pipenv run python src/app.py

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false